---
feature:
  - "(feature|feat)"

critical:
  - "(critical|urgent)"

bug:
  - "bug"

documentation:
  - "(documentation|docs)"

continuous integration:
  - "ci"

build:
  - "build"

chore:
  - "chore"

fix:
  - "fix"

refactor:
  - "refactor"

revert:
  - "revert"

style:
  - "style"

test:
  - "test"

enhancement:
  - "enhancement"

question:
  - "question"

"priority: critical":
  - "priority: critical"

"priority: high":
  - "priority: high"

"priority: medium":
  - "priority: medium"

"priority: low":
  - "priority: low"

"in progress":
  - "in progress"

"needs review":
  - "needs review"

blocked:
  - "blocked"

closed:
  - "closed"

frontend:
  - "frontend"

backend:
  - "backend"

api:
  - "api"

ui/ux:
  - "ui/ux"

"good first issue":
  - "good first issue"

easy:
  - "easy"

medium:
  - "medium"

hard:
  - "hard"

major:
  - "major"

minor:
  - "minor"

fixed:
  - "fixed"

wontfix:
  - "wontfix"

duplicate:
  - "duplicate"

invalid:
  - "invalid"

help wanted:
  - "help wanted"

performance improvements:
  - "performance improvements"

release:
  - "release"

"status: can't reproduce":
  - "status: can't reproduce"

"status: confirmed":
  - "status: confirmed"

"status: needs information":
  - "status: needs information"

"status: wont do/fix":
  - "(status: status: wont do|status: status: wont fix)"

"type: discussion":
  - "type: discussion"

"type: epic":
  - "type: epic"
